from __future__ import annotations
import uuid

from core.state import TripWeaveState
from core.services.llm_suggestions import generate_suggestions


def make_activity_id(traveller_id: str, place_name: str) -> str:
    """Generates a unique Activity ID by combining the place name and user ID."""
    safe_name = str(place_name).replace(" ", "_").lower()
    slug = traveller_id.split(":")[-1] if ":" in traveller_id else traveller_id

    # Appends a short random string (UUID) to handle visiting the same place twice.
    short_uuid = str(uuid.uuid4())[:4]
    return f"activity:{slug}_{safe_name}_{short_uuid}"


async def generate_alternative_suggestions(state: TripWeaveState) -> dict:
    request = state.get("suggestion_request") or {}

    if not request:
        return {}

    # 1. Call Gemini AI (Now it returns a list of 'objects' instead of simple strings!)
    suggestions = await generate_suggestions(
        mode=request.get("mode", "general"),
        destination=request.get("destination", "your destination"),
        date_reference=request.get("date_reference", "today"),
        interests=request.get("interests", []),
        walking_preference=request.get("walking_preference", "unspecified"),
        condition=request.get("condition", "none"),
        current_summary=state.get("final_summary", "Trip update prepared."),
        user_context=state.get("user_context")
    )

    # Extract the actual structured schedule list generated by Gemini.
    activities = suggestions.get("activities", [])

    traveller_id = state.get("traveller_id", "traveller:unknown")
    day_plan_id = state.get("day_plan_payload", {}).get("id")

    # Retrieve existing edges (relationships) from the state to append to them.
    relationship_updates = state.get("relationship_updates", [])

    activity_payloads = []     # Actual activity nodes to be saved in the DB
    alternative_strings = []   # For temporarily displaying text on the frontend UI

    prev_activity_id = None

    # 2. Assemble Graph DB nodes and edges
    for idx, act in enumerate(activities):
        place = act.get("place_name", f"Place_{idx}")
        act_id = make_activity_id(traveller_id, place)

        # [Node Creation] Assemble the Activity dictionary.
        activity_payloads.append({
            "id": act_id,
            "place_name": place,
            "start_time": act.get("start_time", ""),
            "duration_mins": act.get("duration_mins", 60),
            "description": act.get("description", "")
        })

        alternative_strings.append(f"[{act.get('start_time')}] {place} - {act.get('description')}")

        # [Edge 1] Day Plan ➔ (contains) ➔ Activity
        if day_plan_id:
            relationship_updates.append({
                "action": "create",
                "relation": "contains",
                "from": day_plan_id,
                "to": act_id,
            })

        # [Edge 2] Previous Activity ➔ (followed_by) ➔ Next Activity (Routing sequence)
        if prev_activity_id:
            relationship_updates.append({
                "action": "create",
                "relation": "followed_by",
                "from": prev_activity_id,
                "to": act_id,
            })

        # Remember the current ID for the next sequence.
        prev_activity_id = act_id

    # 3. Pack everything into the state updates dictionary and return!
    updates = {
        "alternative_suggestions": alternative_strings,
        "activity_payloads": activity_payloads,         # 🌟 Newly created activity nodes!
        "relationship_updates": relationship_updates    # 🌟 Appended relationship edges
    }

    suggested_summary = suggestions.get("suggested_summary")
    if suggested_summary:
        updates["suggested_summary"] = suggested_summary
        updates["final_summary"] = suggested_summary

    return updates